### ISSUE TITLE
Default character set contains characters that are length 2?

### ISSUE THREAD

**Issue by bertrandom** [UTFeight/RASCII#13]
In the default character set:

```
pub const DEFAULT: &[&str] = &[
    " ", ".", "`", "^", "\"", "\\", ",", ":", ";", "I", "l", "!", "i", ">", "<", "~", "+", "_",
    "-", "?", "]", "[", "}", "{", "1", ")", "(", "|", "\\", "\\/", "/", "t", "f", "j", "r", "x",
    "n", "u", "v", "c", "z", "X", "Y", "U", "J", "C", "L", "Q", "0", "O", "Z", "m", "w", "q", "p",
    "d", "b", "k", "h", "a", "o", "*", "#", "M", "W", "&", "8", "%", "B", "$", "@",
];
```

Doesn't `"\\/"` result in two characters? When I send this sample image into it:
![1uxv8fafhvm-luke-chesser](https://github.com/UTFeight/RASCII/assets/57770/0fb4c272-9808-4f78-98ae-e2ca6cd20027)

This causes the line to not be a uniform length:

<img width="672" alt="-bash 2023-06-04 16-47-03" src="https://github.com/UTFeight/RASCII/assets/57770/e625a822-b1fd-4040-8ccb-40198e41b7dd">

**Comment by RGBCube** [comment]
Thanks for reporting, and yes, it is an oversight, will fix soon

**Comment by RGBCube** [comment]
Should be fixed in the last commit.
