### ISSUE TITLE
Redundant method

### ISSUE THREAD

**Issue by RGBCube** [UTFeight/RASCII#20]
`rascii_art::render(_image)` and `rascii_art::render(_image)_to` accomplish the same thing, and introduce confusing.

The code is also duplicated in the library making it longer to compile and not great in code quality.

**Comment by orhnk** [comment]
String doesn't implement `io::Write`

**Comment by RGBCube** [comment]
> String doesn't implement `io::Write`

It literally does: https://doc.rust-lang.org/std/string/struct.String.html#impl-Write-for-String

**Comment by orhnk** [comment]
That is `fmt::Write` not `io::Write`

**Comment by RGBCube** [comment]
> That is `fmt::Write` not `io::Write`

Oh, right, but then you could remove the duplicates by using fmt::Write only

**Comment by RGBCube** [comment]
because currently the code is duplicated for no gain

**Comment by orhnk** [comment]
It is not redundant to include a stdout function for such API.

But I'll rename the methods to make it more sense

**Comment by RGBCube** [comment]
> It is not redundant to include a stdout function for such API.
> 
> But I'll rename the methods to make it more sense

DRY
